name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: output username
      run: echo ${{ vars.DOCKERHUB_USERNAME }}
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: List files for debugging
      run: |
        pwd
        ls -la
        ls -la scripts/
        
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: cert-automation:latest
